import { bigint, boolean, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const runs = pgTable("tenetkit_runs", {
  runId: text("run_id").primaryKey(),
  status: text().notNull(),
  address: text().notNull(),
  sessionId: text("session_id").notNull(),
  messageId: text("message_id").notNull(),
  messageJson: text("message_json").notNull(),
  messageDigest: text("message_digest").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  executableRefJson: text("executable_ref_json").notNull(),
  executableManifestJson: text("executable_manifest_json").notNull(),
  rootRunId: text("root_run_id").notNull(),
  depth: integer().notNull(),
  maxDepth: integer("max_depth").notNull(),
  maxSubagents: integer("max_subagents").notNull(),
  parentRunId: text("parent_run_id"),
  invocationId: text("invocation_id"),
  activeWaitId: text("active_wait_id"),
  attempt: integer().default(0).notNull(),
  attemptFence: integer("attempt_fence").default(0).notNull(),
  lastSequence: integer("last_sequence").default(-1).notNull(),
  cancellationRequested: boolean("cancellation_requested").default(false).notNull(),
  cancelReason: text("cancel_reason"),
  terminalEventId: text("terminal_event_id"),
  acceptedSequence: bigint("accepted_sequence", { mode: "number" }).notNull(),
  respondedWaitIdsJson: text("responded_wait_ids_json").notNull(),
  driverCheckpointJson: text("driver_checkpoint_json"),
  suspensionJson: text("suspension_json"),
  continuationJson: text("continuation_json"),
  pendingOutcomeJson: text("pending_outcome_json"),
  ownerWorkerId: text("owner_worker_id"),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
})

export const runOperations = pgTable("tenetkit_run_operations", {
  runId: text("run_id").notNull(),
  operationId: text("operation_id").notNull(),
  operationKey: text("operation_key").notNull(),
  kind: text().notNull(),
  status: text().notNull(),
  inputDigest: text("input_digest").notNull(),
  inputJson: text("input_json").notNull(),
  resultJson: text("result_json"),
  errorJson: text("error_json"),
  replayPolicy: text("replay_policy").notNull(),
  attempt: integer().notNull(),
  ownerWorkerId: text("owner_worker_id"),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  startedAt: timestamp("started_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  resolutionIdempotencyKey: text("resolution_idempotency_key"),
  resolutionJson: text("resolution_json"),
})
