import * as SqliteMigrator from "@effect/sql-sqlite-bun/SqliteMigrator"
import { executionMigrations } from "./execution/product-execution-migrations"
import { threadMigrations } from "./thread/product-thread-migrations"
import { transcriptMigrations } from "./transcript/product-transcript-migrations"
import { usageMigrations } from "./usage/product-usage-migrations"

export const migrationNames = [
  "product_baseline",
  "turns",
  "queued_turn_status",
  "execution_extension_pins",
  "turn_prompt_parts",
  "drop_thread_session_id",
  "execution_route_pins",
  "review_fan_out_owners",
  "transcript_projection",
  "thread_summaries",
  "semantic_transcript_projection",
  "queue_state_and_current_transcripts",
  "provider_execution_routes",
  "durable_queue_claims",
  "usage_cursor_checkpoints",
  "pricing_version_checkpoints",
  "thread_search_projection",
  "durable_thread_coordination",
  "turn_stop_intent",
  "usage_projection",
  "materialized_thread_summaries",
  "reconciled_child_trees",
  "consumed_execution_checkpoints",
  "drop_usage_repairs",
  "stable_transcript_unit_order",
  "discriminated_turns",
  "usage_projection_sources",
  "product_route_snapshot",
] as const

export const productMigrations = SqliteMigrator.fromRecord({
  "1_product_baseline": threadMigrations[1],
  "2_turns": threadMigrations[2],
  "3_queued_turn_status": threadMigrations[3],
  "4_execution_extension_pins": executionMigrations[4],
  "5_turn_prompt_parts": threadMigrations[5],
  "6_drop_thread_session_id": threadMigrations[6],
  "7_execution_route_pins": executionMigrations[7],
  "8_review_fan_out_owners": executionMigrations[8],
  "9_transcript_projection": transcriptMigrations[9],
  "10_thread_summaries": threadMigrations[10],
  "11_semantic_transcript_projection": transcriptMigrations[11],
  "12_queue_state_and_current_transcripts": threadMigrations[12],
  "13_provider_execution_routes": executionMigrations[13],
  "14_durable_queue_claims": threadMigrations[14],
  "15_usage_cursor_checkpoints": transcriptMigrations[15],
  "16_pricing_version_checkpoints": transcriptMigrations[16],
  "17_thread_search_projection": threadMigrations[17],
  "18_durable_thread_coordination": threadMigrations[18],
  "19_turn_stop_intent": threadMigrations[19],
  "20_usage_projection": usageMigrations[20],
  "21_materialized_thread_summaries": threadMigrations[21],
  "22_reconciled_child_trees": transcriptMigrations[22],
  "23_consumed_execution_checkpoints": transcriptMigrations[23],
  "24_drop_usage_repairs": usageMigrations[24],
  "25_stable_transcript_unit_order": transcriptMigrations[25],
  "26_discriminated_turns": threadMigrations[26],
  "27_usage_projection_sources": usageMigrations[27],
  "28_product_route_snapshot": executionMigrations[28],
})
