import { Schema } from "effect"

export const TranscriptUnitRow = Schema.Struct({
  unit_key: Schema.String,
  execution_key: Schema.NullOr(Schema.String),
  unit_json: Schema.String,
  unit_order_key: Schema.String,
  durable_parent_id: Schema.NullOr(Schema.String),
  durable_tool_id: Schema.NullOr(Schema.String),
  checkpoint_execution_id: Schema.NullOr(Schema.String),
  checkpoint_is_root: Schema.NullOr(Schema.Finite),
  attachment_parent_execution_key: Schema.NullOr(Schema.String),
  attachment_parent_unit_key: Schema.NullOr(Schema.String),
  attachment_parent_id: Schema.NullOr(Schema.String),
  attachment_parent_order_key: Schema.NullOr(Schema.String),
  attachment_unit_key: Schema.NullOr(Schema.String),
  attachment_unit_execution_key: Schema.NullOr(Schema.String),
  attachment_unit_order_key: Schema.NullOr(Schema.String),
  attachment_unit_tool_id: Schema.NullOr(Schema.String),
  attachment_unit_json: Schema.NullOr(Schema.String),
  turn_id: Schema.String,
  projection_revision: Schema.Finite,
  model_phase: Schema.Finite,
  cost_usd: Schema.NullOr(Schema.Finite),
  projection_version: Schema.Finite,
})
