import { WorkspaceCapabilitySnapshot } from "@rika/product/executor-assignment"
import { runnerProtocolVersion } from "@rika/product/runner-registration"
import { WorkspaceRequest, WorkspaceResponse } from "@rika/product/workspace-capability"
import { Schema } from "effect"
import { SetupCacheKey } from "../workspace/artifact/archive"
import {
  AccessWire,
  BindingContractDigest,
  BindingOutcome,
  BindingRequest,
  EncodedArchive,
  EnvironmentDigest,
  EnvironmentName,
  Fence,
  Generation,
  HelloWire,
  Identifier,
  LeaseEpoch,
  OutputText,
  PtyGap,
  RequestDigest,
  Sequence,
  Sha256,
} from "./message-core"
import {
  CellLifecycleFrame,
  CellRequest,
  CellResponse,
  CellTerminalOutcome,
  HeartbeatWire,
  MachineOutcome,
  MachineRequest,
} from "./message-execution"
import {
  BranchPushOutcome,
  BranchPushRequest,
  CheckpointProposal,
  CredentialWire,
  PtyCreate,
  PtyInput,
  PtyReconnect,
  PtyResize,
  PtyTranscriptChunk,
  QuiescedOperation,
  ReceiptWire,
  ReconnectWelcomeWire,
  RepositoryCheckoutWire,
  RunnerHelloWire,
  WelcomeWire,
  WorkspacePreparationEvidenceWire,
  WorkspacePreparationPhase,
  WorkspaceProof,
} from "./message-workspace"

export const RunnerMessage = Schema.Union([
  Schema.TaggedStruct("RunnerHello", { hello: RunnerHelloWire }),
  Schema.TaggedStruct("ExecutorReconnect", {
    protocolVersion: Schema.Literal(runnerProtocolVersion),
    access: AccessWire,
  }),
  Schema.TaggedStruct("ExecutorHeartbeat", { heartbeat: HeartbeatWire }),
  Schema.TaggedStruct("RunnerGoodbye", { access: AccessWire }),
  Schema.TaggedStruct("LocalCellResult", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    response: CellResponse,
  }),
  Schema.TaggedStruct("CellLifecycle", { access: AccessWire, frame: CellLifecycleFrame }),
  Schema.TaggedStruct("BindingInvoke", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    callId: Identifier,
    requestDigest: RequestDigest,
    request: BindingRequest,
  }),
  Schema.TaggedStruct("MachineResult", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    machineId: Identifier,
    requestDigest: RequestDigest,
    outcome: MachineOutcome,
  }),
])
export type RunnerMessage = typeof RunnerMessage.Type

export const ExecutorMessage = Schema.Union([
  Schema.TaggedStruct("ExecutorHello", {
    hello: HelloWire,
    lifecycle: Schema.Literals(["fresh", "resume", "replacement"]),
    environmentDigest: EnvironmentDigest,
  }),
  Schema.TaggedStruct("ExecutorReconnect", { access: AccessWire }),
  Schema.TaggedStruct("ExecutorHeartbeat", { heartbeat: HeartbeatWire }),
  Schema.TaggedStruct("ExecutorConnectionFailed", {
    access: AccessWire,
    stage: Schema.Literals(["controller", "api", "pty"]),
    message: Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(512)),
  }),
  Schema.TaggedStruct("CredentialRequested", {
    requestId: Identifier,
    access: AccessWire,
    ownerId: Identifier,
    assignmentId: Identifier,
    repositoryId: Identifier,
    workspaceId: Identifier,
    purpose: Schema.Literals(["git-read", "github-read", "branch-push"]),
    publicationId: Schema.optionalKey(Identifier),
    branch: Schema.optionalKey(Identifier),
    ref: Schema.optionalKey(Identifier),
    commitSha: Schema.optionalKey(Schema.String.check(Schema.isPattern(/^[a-f0-9]{40}$/))),
    assignmentGeneration: Generation,
    leaseEpoch: LeaseEpoch,
  }),
  Schema.TaggedStruct("CredentialRevocationRequested", {
    access: AccessWire,
    ownerId: Identifier,
    assignmentId: Identifier,
    repositoryId: Identifier,
    workspaceId: Identifier,
    purpose: Schema.Literals(["git-read", "github-read", "branch-push"]),
    publicationId: Schema.optionalKey(Identifier),
    branch: Schema.optionalKey(Identifier),
    ref: Schema.optionalKey(Identifier),
    commitSha: Schema.optionalKey(Schema.String.check(Schema.isPattern(/^[a-f0-9]{40}$/))),
    assignmentGeneration: Generation,
    leaseEpoch: LeaseEpoch,
  }),
  Schema.TaggedStruct("WorkspacePreparationRequested", {
    access: AccessWire,
    workspaceId: Identifier,
    wakeId: Identifier,
    cold: Schema.Boolean,
    attempt: Generation,
    retry: Schema.Boolean,
  }),
  Schema.TaggedStruct("WorkspacePreparationStarted", {
    access: AccessWire,
    workspaceId: Identifier,
    phase: WorkspacePreparationPhase,
    attempt: Generation,
  }),
  Schema.TaggedStruct("WorkspacePreparationOutput", {
    access: AccessWire,
    workspaceId: Identifier,
    phase: WorkspacePreparationPhase,
    attempt: Generation,
    stream: Schema.Literals(["stdout", "stderr"]),
    text: OutputText,
    redacted: Schema.Literal(true),
    truncated: Schema.Boolean,
  }),
  Schema.TaggedStruct("WorkspacePreparationReady", {
    access: AccessWire,
    workspaceId: Identifier,
    phase: WorkspacePreparationPhase,
    attempt: Generation,
    evidence: WorkspacePreparationEvidenceWire,
  }),
  Schema.TaggedStruct("WorkspacePreparationFailed", {
    access: AccessWire,
    workspaceId: Identifier,
    phase: WorkspacePreparationPhase,
    attempt: Generation,
    message: Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(2_048)),
    retryable: Schema.Boolean,
  }),
  Schema.TaggedStruct("ExecutorWorkspaceReady", {
    access: AccessWire,
    proof: WorkspaceProof,
    capabilities: WorkspaceCapabilitySnapshot,
  }),
  Schema.TaggedStruct("ExecutorQuiesced", {
    access: AccessWire,
    requestId: Identifier,
    operations: Schema.Array(QuiescedOperation),
    checkpoint: CheckpointProposal,
  }),
  Schema.TaggedStruct("SetupCacheLookup", {
    access: AccessWire,
    requestId: Identifier,
    key: SetupCacheKey,
  }),
  Schema.TaggedStruct("SetupCacheProposed", {
    access: AccessWire,
    requestId: Identifier,
    key: SetupCacheKey,
    archive: EncodedArchive,
  }),
  Schema.TaggedStruct("BranchPushResult", {
    access: AccessWire,
    publicationId: Identifier,
    branch: Identifier,
    commitSha: Schema.String.check(Schema.isPattern(/^[a-f0-9]{40}$/)),
    outcome: BranchPushOutcome,
  }),
  Schema.TaggedStruct("PtyOpened", { access: AccessWire, pty: PtyCreate }),
  Schema.TaggedStruct("PtyOutput", { access: AccessWire, ptyId: Identifier, chunk: PtyTranscriptChunk }),
  Schema.TaggedStruct("PtyReplayGap", { access: AccessWire, ptyId: Identifier, gap: PtyGap }),
  Schema.TaggedStruct("PtyDisconnected", { access: AccessWire, ptyId: Identifier, cursor: Sequence }),
  Schema.TaggedStruct("PtyTerminated", { access: AccessWire, ptyId: Identifier, cursor: Sequence }),
  Schema.TaggedStruct("WorkspaceResponse", { access: AccessWire, response: WorkspaceResponse }),
  Schema.TaggedStruct("CellResult", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    response: CellResponse,
  }),
  Schema.TaggedStruct("CellLifecycle", { access: AccessWire, frame: CellLifecycleFrame }),
  Schema.TaggedStruct("BindingInvoke", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    callId: Identifier,
    requestDigest: RequestDigest,
    request: BindingRequest,
  }),
  Schema.TaggedStruct("MachineResult", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    machineId: Identifier,
    requestDigest: RequestDigest,
    outcome: MachineOutcome,
  }),
])
export type ExecutorMessage = typeof ExecutorMessage.Type

export const ApiMessage = Schema.Union([
  Schema.TaggedStruct("ExecutorWelcome", { welcome: WelcomeWire }),
  Schema.TaggedStruct("ExecutorReconnected", { welcome: ReconnectWelcomeWire }),
  Schema.TaggedStruct("PhaseEnvironmentGranted", {
    phase: Schema.Literals(["setup", "runtime"]),
    digest: EnvironmentDigest,
    operationKey: Schema.NullOr(Identifier),
    values: Schema.Record(EnvironmentName, Schema.String),
    redactedNames: Schema.Array(EnvironmentName),
  }),
  Schema.TaggedStruct("LeaseReceipt", { receipt: ReceiptWire }),
  Schema.TaggedStruct("LocalCellReceipt", { access: AccessWire, operationKey: Identifier, attempt: Sequence }),
  Schema.TaggedStruct("CheckpointAccepted", { checkpointId: Identifier, contentDigest: Sha256 }),
  Schema.TaggedStruct("RepositoryCredential", { credential: CredentialWire }),
  Schema.TaggedStruct("WorkspacePreparationAssigned", {
    access: AccessWire,
    workspaceId: Identifier,
    wakeId: Identifier,
    cold: Schema.Boolean,
    attempt: Generation,
    retry: Schema.Boolean,
    templateBuildId: Identifier,
    bindingContractDigest: BindingContractDigest,
    checkout: Schema.NullOr(RepositoryCheckoutWire),
  }),
  Schema.TaggedStruct("WorkspacePreparationRetry", { fence: Fence, attempt: Generation }),
  Schema.TaggedStruct("WorkspaceAccepted", { fence: Fence }),
  Schema.TaggedStruct("Quiesce", { fence: Fence, requestId: Identifier }),
  Schema.TaggedStruct("SetupCacheResult", {
    requestId: Identifier,
    archive: Schema.NullOr(EncodedArchive),
  }),
  Schema.TaggedStruct("SetupCacheAccepted", { requestId: Identifier }),
  Schema.TaggedStruct("BranchPush", { request: BranchPushRequest }),
  Schema.TaggedStruct("PtyCreate", { fence: Fence, request: PtyCreate }),
  Schema.TaggedStruct("PtyInput", { fence: Fence, request: PtyInput }),
  Schema.TaggedStruct("PtyResize", { fence: Fence, request: PtyResize }),
  Schema.TaggedStruct("PtyDisconnect", { fence: Fence, ptyId: Identifier }),
  Schema.TaggedStruct("PtyReconnect", { fence: Fence, request: PtyReconnect }),
  Schema.TaggedStruct("PtyTerminate", { fence: Fence, ptyId: Identifier }),
  Schema.TaggedStruct("WorkspaceRequest", { fence: Fence, request: WorkspaceRequest }),
  Schema.TaggedStruct("CellExecute", { request: CellRequest }),
  Schema.TaggedStruct("CellCancel", { access: AccessWire, operationKey: Identifier, attempt: Sequence }),
  Schema.TaggedStruct("CellReplay", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    afterCursor: Sequence,
  }),
  Schema.TaggedStruct("CellTerminalReceipt", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    cursor: Sequence,
  }),
  Schema.TaggedStruct("CellTerminalSuperseded", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    cursor: Sequence,
    outcome: CellTerminalOutcome,
    response: CellResponse,
  }),
  Schema.TaggedStruct("BindingResult", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    callId: Identifier,
    requestDigest: RequestDigest,
    outcome: BindingOutcome,
  }),
  Schema.TaggedStruct("MachineExecute", {
    access: AccessWire,
    operationKey: Identifier,
    attempt: Sequence,
    machineId: Identifier,
    requestDigest: RequestDigest,
    request: MachineRequest,
  }),
  Schema.TaggedStruct("Fenced", { fence: Fence, message: Schema.String }),
])
export type ApiMessage = typeof ApiMessage.Type
